language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: W3NQr7Yru9uAtAWFRUVpZQT0dPqFfXOnBpEETacITKrngWUY7me1OceLkc3UsDdlkaPSA7C4fEZU70ojI2QlCHhwJgk+kiHxgyTOrQJ5TSTnSHh1Y0Vc0poQ3R2dxXjgnXzfvHkOLRm13ZstOtT7wQIR7Icle2stuQtWDV3T5B2/RWa+g34uVqZS9t8Wjfcei90DI229rdMG3UcD+RbLsdklUY0lBBWX451vgo82LQZZ0kG29hkfqNU6O3yQf6rJEAqL8rk8n0JQ9xZhHe4ONcLByW96IUSPqNfN+81NgYyr7FYQ2cdMQuIDb+9iNWgsO+UudGdQyRzNOIrGBUDK8CQ+mGvvmLnm749O4OZp3wNl0a9qWpvwJ8ABGyFkJr1IhoNjiJHhAIRzgGgTvxWj+CQgGWMrG+ctAa8TCk5/N8td7EOQuvDnosI/qrZ0wLbmmXtPZzOM1h3ycIFBJo7nJoLsbCGTdH155mlUaKtATcd6khRFI3/svbjHsfZasg9n1MTDJqI8dVsNG8kcQD+Ihisgui4xWrEWhJo+YN3BZHTJoQS86e8cs2OVrJItENQ9loiSGY0gH5tmJoUCLfJh1isK/djR7+urHBF0BUJoNf0V7PWsFMz2RoM7Jzmawv0K/C630dKsRcncrwS8tplvl69itV6aDK0I79yq40DEM8Y=
  on:
    tags: true
  skip_cleanup: true
  server: https://test.pypi.org/legacy/
