language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: __token__
  password:
    secure: tVuLHLoVfDoFZ59pzYSQTFjuUyqgoNi9kpZWldtl+FafLl8BfQSG2Lu7HZdypxweOa84JCBS/K7ozQYyYQrQQNRGVUw9fU1zjAq6DeYDyZ5b/qSKNX7nGU6CYclim5qHdnDtrWQpwLOx92gsXg+oHDcyS5Hm8gGUtePo1cWSqzN+xVTZ6I2Sjpl6dhI04I6i54B21RjdJmSqfslqx6IELuB78cOtJXDmGudJGbiotCOvJQ4weYIwkRFhWmdWnvkJV/POD4sXlxXgT9FDm5FT3MIdVxmqLSdJTLmsUIbZBBYNAsA+ienHmqeN74ivUIVhN2cQ/zQygY3HZr0Kx5auo9BG+YClOUS64bnIxGBvJk/aESLnACVkxjZeoNP/mGI6TGYl3f9zCXLf/wrfPSJElLHksq4UMufGhRynAhLXwTuHQ6ybI5CbiKRWubrFPa7b5B4rCtl5AJOqa4Z04lY4FD5r9qxSO36qqLankG79rMv8YieckHiY7gYTrNNZRgZsNDr+I1csCGQyJanRHBvLQCu1InnOX3Twb1TYi3n58IjWJF/feKVsf4+dGtUaV3PYjZbb/nev3uT8Lx/h3Ma5+r3MstqiZDfjwufntxU5t6q/Swz2Fgizpmri2ZFA8ekTcr2GlxfA4Hz1qswJr9NeknD6gSmhW/x+tu4U7p7iUW4=
  on:
    tags: true
  skip_cleanup: true
