language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: __token__
  server: https://test.pypi.org/legacy/
  password:
    secure: ZsNH+UaTPdP8FR+XmR6Ph9wAqfaEzuqlR+VitsQVGAThgarsVpFYUGwHjZ9zoCdyXdjH9/jQ7qXDRFL4Gwv12PN53/Y7C2lHuoS0bMNjs9xnS9YMlSK3ZXlXzPXEiYmLZ+rtVAye7vcU3oVVAWZWhS23uXGh9lEYas+jiJ7ivmTcz1V5Cc1AQged9UcVstVWt/KDm7I5n/aUVMvnYFbKC7W5oA15n6YgIp6NT0oSRiS4HbavgnpfFowf44d3215+8exo0qEs/06iy8HvT40vxJ1teFUlMAS2V5VIA9xdjTJXtG4iJe+UBGlq6Gy7SrQzGqk3ijsqXsXEugbY3FPeSiNTIpqWfJv1c4vNG5d8pbqkeHEMFgPVmuwAkBNyLVpGnqIb4cScHX7QsumPudMrPtvjNWHNwN70q1oXsE3sN+cSn9lTjJDJ2wSJBh7KlzKyraVwcqHjBakN/s+ot+lw4NNuSVWScMqdoG5xLh/ALK5a018fyYQ/eLnS3sBNbg4+Ls4Zs8AYJcNYYRCCwkzQ7nomWH+xY3GgncbHvVEDZLQCxXVryFQglk/+fTsa5JPDmkiSaahiTX9FFpm1rjzjbtnJqQeYaAQkiBxpVYJye7hTKyrN4xpeYRyGcxcgmNAnldQu0+VhC1JtnFx1QJmkjb7ncqJ5uHJwGP/7j8wxZUQ=
  on:
    tags: true
  skip_cleanup: true
