language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: __token__
  password:
    secure: yYTR25X+KlHOw0SMZUtjXlFR3h8NKL0zdeF29ljkXOUTRS1CXUCxsffAHfzij/+ZpJBXVsAbLkgg1c1xh4BC6K4gsvCPnxRIbPVcmc5nU6v7t3XAhR56btqDJZn90UazstNYJbksFj+e9o9upF3OXDANR/ckoOIqMUagYA50BXC4NKvth9PsI4nc+gMZF7sZAL0uAkKPPI0IAtvFMaqyiQfP0c5+sy+bu1fViWjXrylaOLp5uMUU0Kz5mfoAdZpphbKoaw7eJQvUyOmO37fO2XyyH1nkOaYu3fW7asZ6/yXVXEgSupc+6ia6PIeKE36s+F3Ngd9aovSMuJWfRn8m5B5sfyQqlL/Fxy6Q4DEz4hneLpQixvUFzh2qS/K6G0+hBQSQ/QMnFHaac8T3GMbAIlmqTKc9V7yFOia0xEL9KdqArrSSBpKEmryGKR7JuLB5sbYIa5uYNYcSprjj47/xZBhL+pEeYM4zuE5TDdU4RZwKAhwMnPhkkbkMlyCnRqmgndhhNCdbSJdIVRukg/WiPDHkmzF4YvOccap/a8JWb6lNX1u3BmjCHLq0nZ+9NCXEyP9SfyGpgLMmmwRpBEMCJcJChxEW6AVa4arLmgAsbXfqrRRQTbnb8bxlZ4D00tHfGkTxD5AB8YhAenf8gx+0UhbKj46dX3jzMuA9CLBm0Rg=
  on:
    tags: true
  skip_cleanup: true
  server: https://test.pypi.org/legacy/
