language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: __token__
  password:
    secure: ikp55RHKvAeDiEUkWklxhpp+MbQRLrk4HTj5Igo0j0EG58kJ8/oGeJZDvq8f4zr105JE64IQJETNZilB51MuzFAE1Ctf63WK6YNJfKSxYe6oMNejFf7Mz3GLia94PazCj42eFkja8l2183EOJOzdHqZA7ygoAyXWKdhpes+Y2rWPGiUPLCPWd1UYZDXZv26sMeuRtZBkRch8wLF73/VCrDkzVeR7J5VPHaJlXYX8htsdqrUWuFUuHZI7XeCb1SdvQlgyzcMlX9AuahYwAu4iz05Eur4xvyeZuIKodF1hnIuAVxd4dAVrfLW3JBQ9tLXFCJ+DDjfXQDQlkIZ2BY+7HLo3W2fbBBCqGgAr39UHYzxF0TuWkdxd8NKlftZAN+nwm4WzazJMgiTqh2TKZeYrB/x+0fanibm6w3FXX3EWXCEhEUt5WNDwLnjfjnzBua5ouCpXom87ACUJedIJ/h5eZN4hBPQQpGBtuVi4qGn3alpYAasRj7dnWdjyO4RExqShxN6l8ciQDa9CUlZB+IkhdF1F9+hpcDwTvhbgclFqz4BgeMxiZrYwxevtyeARBUQbRqQamInp5kZbcYBBQuLjlB180sW8l8BTmrwWKTOqN+W1deAzYy63iYxmugOxCi5CjhGQJOui5xjJF7gBOxuoSzOLXC4lDxCmn1vQVI/Cy4c=
  on:
    tags: true
  skip_cleanup: true
