language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install nose2
- pip install codecov
install:
- pip install .
script:
- export NUMBA_DISABLE_JIT="1" && nose2 --plugin nose2.plugins.junitxml --with-coverage
  --coverage pandora --coverage-report xml -X
after_success:
- codecov
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- echo 'update version according to the tag name'
- sed -i "/version=/d" setup.py
- sed -i 's|long_description=readme(),|long_description=readme(),\n      version='"'${TRAVIS_TAG}'"',|'
  setup.py
- cat setup.py | grep version
deploy:
  provider: pypi
  username: __token__
  password:
    secure: JOG+Hmk76K2WrYng3q9j44Hxws0u4afURamGnkP1MpMIcxXngKKN2sybpQQzlAo/dk+DX+GzhHvoqH2OEOMQfOBf6n922DPS9+aFZoC+qDPgTaipoePWZ448D7tjG87nxMASae1jTjH6VBkHL+gU9kwKixxkgYJmOmL+37kEIHTEY4QN8zBk53tGv6vDmnW+tAzygo8HkKe/bozpZ/I4wO32PEVdRZ9iHjHEs3Gbmx8o2vc/bXCcDzov+vX7f97Gl7czj69twH5NeUZO5q6icHVR8Ya/JNav6aHpO6dhi8X2a8hW6/1ZK+LEgQh//bDysDsvHWFuCvs9lQzM2neY07cOxhrWhDiYpmcAdFskpsz2k8bspZcQsrS5M/uw43zb6GIriqB2zzvj+PtrDxuUX7QoRMMVjTDZgHnnxUScg3yK+VLNcPrqbU11ggMU3dQJfnRMFREwCHx8eDnMTVqm24QQNtjg9hqCIpwpzxzqR+YE1VsYn48C+McuUys20q4LltwUmIH3TKXtKblpQUlgyE/GYH0pLodbSMzQRkeB8HaET1NGqljzNRLq55OsdSsafkOfvnn6orZji0fMgG6tseACJIGsaO32nuaY8cfIHHPvpmbLsHt/sWrqSRDusEBai7xUtRuOMdnCPsHEapGwz/4paeni9o5OmulekLZX3UQ=
  on:
    tags: true
  skip_cleanup: true
  server: https://test.pypi.org/legacy/
